EMAIL_EXTRACTOR_DEPTH = 3
EMAIL_EXTRACTOR_MAX_URLS = 50

TOR_SOCKS_PORT = 7000
TOR_CONTROL_PORT = 9051
TOR_EXIT_NODES = '{US}'
TOR_EXCLUDE_NODES = '{A1}, {??}'
TOR_MAX_CIRCUIT_DIRTINESS = '200'
TOR_PASSWORD = ''

PUBLIC_PROXY_TIMEOUT = 10
URLLIB_TIMEOUT = 10

MAXIMUM_RETRY = 20

DB_NAME = ''
DB_HOST = 'localhost'
DB_PORT = 27017
DB_PREFIX = ''